// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0FiINpK8awvUgheRZOe1I4nbTpWtPNGw',
    appId: '1:117768483897:web:83c63ecd5b33a5ef40c9e8',
    messagingSenderId: '117768483897',
    projectId: 'teegg-bc644',
    authDomain: 'teegg-bc644.firebaseapp.com',
    storageBucket: 'teegg-bc644.appspot.com',
    measurementId: 'G-QDSPERSXQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOjKU1RMCMXUO4zYxPPs_7c4PX6G11LOg',
    appId: '1:117768483897:android:371ba795da6d45cc40c9e8',
    messagingSenderId: '117768483897',
    projectId: 'teegg-bc644',
    storageBucket: 'teegg-bc644.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_rAHuy-qGjozFfG8dNIx8mWxGDduJG08',
    appId: '1:117768483897:ios:5da634624d1e22b640c9e8',
    messagingSenderId: '117768483897',
    projectId: 'teegg-bc644',
    storageBucket: 'teegg-bc644.appspot.com',
    iosClientId: '117768483897-ffon7rbjukolb4ktkeupn9om5j1s1l2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.teegg',
  );
}
